name: nginx

services:
  nginx:
    build: .
    # image: nginx:alpine
    volumes:
      - type: bind
        source: ./default-config.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:8080
    restart: on-failure
    networks:
      - main-net