# networks:
#   main-net:
#     external: false

# x-kong-config:
#   KONG_DATABASE: postgres
#   KONG_PG_DATABASE: kong
#   KONG_PG_HOST: db
#   KONG_PG_USER: kong
#   KONG_PG_PASSWORD: kong
  # KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password

volumes:
  kong_prefix_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kong_tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
    

services:
  kong-migrations:
    image: kong:latest
    command: kong migrations bootstrap
    # profiles: [ "database" ]
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    # secrets:
    #   - kong_postgres_password
    networks:
      - main-net
    restart: on-failure

  kong-migrations-up:
    image: kong:latest
    command: kong migrations up && kong migrations finish
    # profiles: [ "database" ]
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    # secrets:
    #   - kong_postgres_password
    networks:
      - main-net
    restart: on-failure
  
  kong:
    image: kong:latest
    user: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_LISTEN: "0.0.0.0:8002"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PREFIX: /var/run/kong
    # secrets:
    #   - kong_postgres_password
    networks:
      - main-net
    ports:
      - "0.0.0.0:8000:8000/tcp"
      - "0.0.0.0:8443:8443/tcp"
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      # - 8003:8003
      # - 8004:8004
    restart: on-failure:5
    read_only: true
    volumes:
      - kong_prefix_vol:/var/run/kong
      - kong_tmp_vol:/tmp
      - ./config:/opt/kong
    security_opt:
      - no-new-privileges
    # deploy:
    #   mode: replicated
    #   replicas: 2

  db:
    image: postgres:latest
    # profiles: [ "database" ]
    networks:
      - main-net
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    # secrets:
    #   - kong_postgres_password
    restart: on-failure
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - /home/anirudh/kong_data:/var/lib/postgresql/data
